import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Board from '../components/board';
import Clock from '../components/clock';
import Todo from '../components/Todo';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Chuck API</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Board />
				<Clock />
				<Todo />
			</main>
		</div>
	);
};

export default Home;
